import EngineeringIcon from "@mui/icons-material/Engineering";
import CleaningServicesOutlinedIcon from "@mui/icons-material/CleaningServicesOutlined";
import {
  IconTrash,
  IconServer2 as ServerIcon,
  IconChevronDown as ExpandMore,
  IconChevronUp as ExpandLess,
  IconSquareRoundedPlus as SquarePlus,
  IconFolderPlus as FolderPlus,
  IconUserPlus as UserPlus,
  IconUsers as Users,
  IconUser as User,
  IconVideo as Video,
  IconFaceId as ScanFace,
  IconWashDryShade as Cleaning,
  IconChartDots3 as ChartDots,
  IconCameraUp as CameraUp,
  IconCameraPlus as CameraPlus,
  IconPlayerPause as Pause,
  IconCircleX as XCircle,
  IconVolume as Volume1,
  IconVolume2 as Volume2,
  IconMapSearch as Map,
} from "@tabler/icons-react";

import { HardDrive, Trash2, Play } from "lucide-react";

export {
  EngineeringIcon,
  CleaningServicesOutlinedIcon,
  IconTrash,
  ServerIcon,
  ExpandMore,
  ExpandLess,
  HardDrive,
  SquarePlus,
  FolderPlus,
  UserPlus,
  Users,
  User,
  Video,
  Trash2,
  ScanFace,
  Cleaning,
  ChartDots,
  Play,
  CameraUp,
  CameraPlus,
  Pause,
  XCircle,
  Volume1,
  Volume2,
  Map,
};
